### PR TITLE
Revert "Update devcontainer.json"

### PR DESCRIPTION
**Pull request by shem8**
Reverts trywilco/Anythink-Market-Public#25

### CODE REVIEW

**Review by darmalovan — APPROVED** [review]

**Comment by darmalovan** [comment]
@shem8 can you point me to a repo the docker didn't start?

**Comment by shem8** [comment]
https://github.com/ObelusFamily/Anythink-Market-8ira853j

**Comment by darmalovan** [comment]
> https://github.com/ObelusFamily/Anythink-Market-8ira853j

I created a codespace instance from this repo and `docker` is running
image

**Comment by shem8** [comment]
So I have no idea why it sometimes doesn't work=|

**Pull request merged**
