### PR TITLE
move k8s file for workflows directory

### PR DESCRIPTION
**Pull request by esapir**

### CODE REVIEW

**Comment by esapir** [comment]
> 

Yes, this is already the case today

**Comment by stellaanavi** [comment]
This is not the case today
Only the actions under `.github/workflows/` will be executed upon trigger 
Moving k8s.yml to `.github/workflows/` means, every push to `Anythink-Market-Public@main` will run Build and deploy to Kubernetes

**Comment by esapir** [comment]
> This is not the case today Only the actions under `.github/workflows/` will be executed upon trigger Moving k8s.yml to `.github/workflows/` means, every push to `Anythink-Market-Public@main` will run Build and deploy to Kubernetes

mmm.. got it. In this case, let's move it to the Engine. I will modify the PR to remove the file

**Comment by stellaanavi** [comment]
Is k8s should be managed by us? should it be managed by the users in some quests?

**Comment by esapir** [comment]
> Is k8s should be managed by us? should it be managed by the users in some quests?

Well, it manages deployment to our K8s cluster and it makes sense that we control this completely. So yes, it should probably move to the Engine

**Review by stellaanavi — APPROVED** [review]

**Pull request merged**
